"use client";
import Link from "next/link";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "@/lib/supabase/client";

function PasswordField({name,label,confirm=false}:{name:string;label:string;confirm?:boolean}){const [visible,setVisible]=useState(false);return <div className="field"><label htmlFor={name}>{label}</label><div className="password-wrap"><input id={name} name={name} type={visible?"text":"password"} minLength={6} autoComplete={confirm?"new-password":"current-password"} required placeholder={confirm?"Retype your password":"At least 6 characters"}/><button className="password-eye" type="button" aria-label={visible?`Hide ${label.toLowerCase()}`:`Show ${label.toLowerCase()}`} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}><span aria-hidden="true">◉</span><i>{visible?"Hide":"Show"}</i></button></div></div>}

export default function AuthForm({mode}:{mode:"login"|"signup"}){const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage("");const f=new FormData(e.currentTarget),email=String(f.get("email")),password=String(f.get("password")),confirmation=String(f.get("password_confirmation")||"");if(mode==="signup"&&password!==confirmation){setMessage("Passwords do not match. Please retype them.");return}setBusy(true);const db=createClient();if(mode==="login"){const {error}=await db.auth.signInWithPassword({email,password});if(error){setMessage(error.message);setBusy(false);return}router.replace("/campaigns");router.refresh()}else{const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:`${location.origin}/campaigns`}});if(error){setMessage(error.message);setBusy(false);return}if(data.session){router.replace("/campaigns");router.refresh()}else{setMessage("Check your email to confirm your account, then log in.");setBusy(false)}}}return <main className="auth-page"><section className="auth-intro"><Link className="brand light" href="/login">Healing Echoes <span>✦</span></Link><div><div className="eyebrow">Content that carries your voice</div><h1>Share your work<br/>with the world.</h1><p>Turn one healing offering into a complete, authentic campaign in minutes.</p></div><small>Made gently for healers and wellness practitioners.</small></section><section className="auth-panel"><form className="auth-card" onSubmit={submit}><div className="mobile-auth-brand">Healing Echoes ✦</div><div className="eyebrow">{mode==="login"?"Welcome back":"Begin your journey"}</div><h2>{mode==="login"?"Log in to your studio":"Create your account"}</h2><p className="muted">{mode==="login"?"Your campaigns are waiting for you.":"Start creating content that sounds like you."}</p><div className="field"><label htmlFor="email">Email address</label><input id="email" name="email" type="email" autoComplete="email" required placeholder="you@example.com"/></div><PasswordField name="password" label="Password"/>{mode==="signup"&&<PasswordField name="password_confirmation" label="Retype password" confirm/>}{message&&<div className={message.startsWith("Check")?"notice":"error compact"} role="status">{message}</div>}<button className="auth-submit" disabled={busy}>{busy?"Please wait…":mode==="login"?"Log in":"Create account"}</button><p className="auth-switch">{mode==="login"?"New to Healing Echoes? ":"Already have an account? "}<Link href={mode==="login"?"/signup":"/login"}>{mode==="login"?"Create an account":"Log in"}</Link></p></form></section></main>}
